apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mr-agent-staging
resources:
  - ../../base
images:
  - name: mr-agent-api
    newTag: staging
  - name: mr-agent-web
    newTag: staging
patches:
  - path: patch-api-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: patch-api-ingress.yaml
  - path: patch-web-ingress.yaml
  - target:
      kind: Namespace
      name: mr-agent
    patch: |
      - op: replace
        path: /metadata/name
        value: mr-agent-staging
